//constants for fetching all posts
export const FETCH_ALL_POSTS_REQUEST = 'FETCH_ALL_POSTS_REQUEST';
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS';
export const FETCH_ALL_POSTS_ERROR = 'FETCH_ALL_POSTS_ERROR';

//constants for fetching user posts
export const FETCH_USER_POSTS_REQUEST = 'FETCH_USER_POSTS_REQUEST';
export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_ERROR = 'FETCH_USER_POSTS_ERROR';

//constants for fetching posts with id
export const FETCH_SELECTED_POST_REQUEST = 'FETCH_SELECTED_POST_REQUEST';
export const FETCH_SELECTED_POST_SUCCESS = 'FETCH_SELECTED_POST_SUCCESS';
export const FETCH_SELECTED_POST_ERROR = 'FETCH_SELECTED_POST_ERROR';

//constants for deleting posts 
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';